### ISSUE TITLE
Bug with long words

### ISSUE THREAD

**Issue by victorbenichoux** [quentinjuarez/paint-emoji#1]
Hi there!

I have an issue with the "Text" functionality of PaintEmoji. It breaks whenever I enter a word that is longer than 9 characters. Console does not show any error. 

This probably has to do with the line break logic implemented here https://github.com/quentinjuarez/paint-emoji/blob/aed3d6c0747547b25f9e1bbb9c14c867b75aadfe/src/components/Draw/TextPanel.vue#L71. The current implementation does not allow splitting inside of words.

Thanks for the hard work.

**Comment by Bv-Lucas** [comment]
Hi

I am facing this issue too, it is preventing my company migration to PaintEmoji, do we have a timeline for the fix? 

Thanks @quentinjuarez for this superb app, hope this gets fixed soon

**Comment by abrajeux** [comment]
Hey all,

Same here since last release,
Plz fix

**Comment by VictorRevnic** [comment]
Hey everyone,

It seems like quite a few of us are experiencing this issue with the "Text" functionality in PaintEmoji. It's definitely impacting usability, especially for those of us considering migrating to the app for company use.

@quentinjuarez , we appreciate your hard work on this app and the creativity it fosters. Could we possibly get an update on when we might expect a fix for this? It would be really helpful for planning purposes.

Looking forward to hearing back and thanks again for your efforts!

**Comment by quentinjuarez** [comment]
Hi everyone,

Thank you all for bringing this issue to my attention. I apologize for any inconvenience it has caused. I'll investigate the issue with the "Text" functionality in PaintEmoji and work on fixing it as soon as possible.

I understand the importance of this fix. I'll keep you updated on the progress and aim to provide a solution in a timely manner.

Thanks for your patience and continued support.

**Comment by VinsonPaul** [comment]
Hi.

Our company team spirit is based solely on this feature, and failing to find a solution could cause a major productivity breakdown.
It is hardly usable as it is and we hope you'll be able to solve this issue as soon as possible.

Thank you for the swiftness and reactivity addressing the matter. 

Looking forward to the next update.
